module-3/06_Automated_Functional_Testing_with_Selenium/lecture-student/src/main/java/com/techelevator/fbn/model/MortgageLoanEstimate.java
package com.techelevator.fbn.model;


public class MortgageLoanEstimate {

	private int loanAmount;
	private int loanTermInYears;
	private double interestRate;

	public MortgageLoanEstimate(int loanAmount, int loanTermInYears, double interestRate) {
		this.loanAmount = loanAmount;
		this.loanTermInYears = loanTermInYears;
		this.interestRate = interestRate;
	}
	
	public DollarAmount getMonthlyPayment() {
		int loanTermInMonths = loanTermInYears * 12;
		double monthlyInterestRate = interestRate / 12;
		double payment = loanAmount*((monthlyInterestRate * Math.pow(1 + monthlyInterestRate, loanTermInMonths)) / (Math.pow(1+monthlyInterestRate, loanTermInMonths) - 1));
		return new DollarAmount((int)(payment * 100));
	}

	public int getLoanAmount() {
		return loanAmount;
	}

	public int getLoanTermInYears() {
		return loanTermInYears;
	}

	public double getInterestRate() {
		return interestRate;
	}
}

module-3/06_Automated_Functional_Testing_with_Selenium/lecture-student/src/main/webapp/WEB-INF/jsp/homePage.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<section class="account">
  <img src="img/piggybank.png" alt="Start Savings">
  <h2 id="savings" class="heading">Start Saving</h2>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sagittis maximus commodo. Donec vestibulum ac elit sed dignissim. Cras eleifend molestie odio, vel malesuada dolor suscipit vitae. Phasellus non tortor quis nibh consequat condimentum. Mauris interdum, quam eu sodales porttitor, elit quam molestie ipsum, dictum rutrum orci neque eget sapien. Sed ac scelerisque nulla. Cras blandit erat nec dolor iaculis, id accumsan dui viverra. Sed sit amet augue ex. Nullam et blandit erat. Aliquam in dui vel nisl bibendum mollis in vel ipsum. Nunc scelerisque ex non nulla rhoncus porta. Suspendisse est elit, eleifend et facilisis at, porttitor sed nisl. Sed ante libero, accumsan quis lobortis ac, consectetur id eros.
  </p>
  <ul>
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
  </ul>
</section>
<section class="account">
  <img src="img/checkandpen.png" alt="Open Checking">
  <h2 id="checkings" class="heading">Open Checking</h2>
  <p>
    Integer at vestibulum libero. Nullam suscipit luctus est ac faucibus. Mauris non nibh elit. Nulla porta at velit ac gravida. Vivamus viverra ante at tortor ultricies mollis. Nam commodo, ante eu volutpat efficitur, tortor ex mollis est, ut finibus ante velit cursus ligula. Nulla augue nibh, faucibus ac mollis nec, commodo blandit urna. Phasellus vestibulum lacus ante, vel ullamcorper velit fringilla nec. Fusce rhoncus urna ut magna venenatis efficitur nec eget augue. Nam tincidunt neque eu ligula hendrerit, ac convallis sem hendrerit. Ut ornare, nisi non dignissim commodo, augue nibh pellentesque tortor, a porttitor est erat vel arcu. Integer in elit non lorem iaculis tincidunt id eu arcu.
  </p>
  <p>
  	<c:url var="checkingApplicationHref" value="/checkingApplication/" />
  	<a href="${checkingApplicationHref}">Open a New Account</a>
  </p>
</section>
<section class="account">
  <img src="img/dollarsign.png" alt="Bridge the Gap">
  <h2 id="loans" class="heading">Loans</h2>
  <p>
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis est lorem, porta quis luctus vel, iaculis quis libero. Ut sodales dapibus lacinia. Cras vehicula pharetra arcu, egestas egestas mi aliquam ac. Donec tempus justo suscipit felis eleifend laoreet. Aenean blandit dolor est, sed suscipit metus luctus et. Vivamus fermentum sem in mi cursus, id porta sapien dapibus. Phasellus et dolor et purus suscipit cursus vel eu elit. Nulla dictum est molestie purus cursus tincidunt. Vivamus dictum sapien eget dui faucibus, quis cursus leo tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Fusce venenatis eros non neque mollis posuere. Maecenas felis nisi, feugiat a faucibus nec, luctus sit amet dui.
  </p>
  <p>
  	<a href="mortgageCalculatorInput">Mortgage Payment Calculator</a>
  </p>
</section>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

module-3/06_Automated_Functional_Testing_with_Selenium/lecture-student/src/main/webapp/WEB-INF/jsp/mortgageCalculatorInput.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/common/header.jsp">
	<c:param name="subTitle" value="Mortgage Calculator" />
</c:import>

<h2>Mortgage Calculator</h2>
<c:url var="formAction" value="/mortgageCalculatorResult" />
<form method="GET" action="${formAction}">
	<div class="formInputGroup">
		<label for="loanAmount">Loan Amount:</label> 
		<input type="text" name="loanAmount" id="loanAmount" />
	</div>
	<div class="formInputGroup">
		<label for="loanTerm">Loan Term:</label> 
		<select name="loanTerm"	id="loanTerm">
			<option value="10">10 Years</option>
			<option value="15">15 Years</option>
			<option value="30">30 Years</option>
		</select>
	</div>
	<div class="formInputGroup">
		<label for="rate">Interest Rate:</label> 
		<input type="text" name="rate" id="rate" />
	</div>
	<input class="formSubmitButton" type="submit" value="Calculate Payment" />
</form>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

module-3/06_Automated_Functional_Testing_with_Selenium/lecture-student/src/main/webapp/WEB-INF/jsp/mortgageCalculatorResult.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/common/header.jsp">
	<c:param name="subTitle" value="Mortgage Calculator" />
</c:import>

<h2>Your Calculated Mortgage Payment</h2>

<table id="loanPaymentCalculationResults">
	<tr>
		<th>Loan Amount:</th>
		<td>$<c:out value="${param.loanAmount}" /></td>
	</tr>
	<tr>
		<th>Loan Term:</th>
		<td><c:out value="${param.loanTerm}" /> years</td>
	</tr>
	<tr>
		<th>Interest Rate:</th>
		<td><c:out value="${param.rate}" />%</td>
	</tr>
	<tr>
		<th>Monthly Payment:</th>
		<td><c:out value="${estimate.monthlyPayment}" /></td>
	</tr>
</table>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />